ERROR - 2025-09-27 05:47:12 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\advaya\elderscare\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\advaya\elderscare\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'elders_care', 3309, '', 0)
#1 C:\xampp\htdocs\advaya\elderscare\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\advaya\elderscare\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\advaya\elderscare\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\advaya\elderscare\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\advaya\elderscare\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\advaya\elderscare\app\Controllers\Login.php(48): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\advaya\elderscare\system\CodeIgniter.php(942): App\Controllers\Login->process()
#8 C:\xampp\htdocs\advaya\elderscare\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\advaya\elderscare\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\advaya\elderscare\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\advaya\elderscare\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\advaya\elderscare\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\advaya\elderscare\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\advaya\elderscare\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\advaya\elderscare\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\advaya\elderscare\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\advaya\elderscare\app\Controllers\Login.php(48): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\advaya\elderscare\system\CodeIgniter.php(942): App\Controllers\Login->process()
#7 C:\xampp\htdocs\advaya\elderscare\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\advaya\elderscare\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\advaya\elderscare\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-09-27 05:47:12 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_info`
WHERE `user_mobileno` = :user_mobileno:
AND `user_info`.`deleted_on` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(48): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Login->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
